FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow

RUN mkdir -p /app/mlflow_data

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///app/mlflow_data/mlflow.db", "--default-artifact-root", "file:///app/mlflow_data/artifacts", "--host", "0.0.0.0", "--port", "5000"]